In [3]:
import numpy
a=numpy.array(34)
print(a)
print(type(a))

34
<class 'numpy.ndarray'>


In [4]:
import numpy as np
print(np.__version__)


1.26.4


In [13]:
import numpy as py
a=py.array(23)
print(a)
print(a.ndim)  

23
0


In [14]:
import numpy as py
a=py.array([23,34,5,5])
print(a)
print(a.ndim)

[23 34  5  5]
1


In [11]:
import numpy as py
a=py.array([[23,45,56,76,2],[23,56,78,93,2]])
print(a)
print(type(a))
print(a.ndim) # number of diamentional

[[23 45 56 76  2]
 [23 56 78 93  2]]
<class 'numpy.ndarray'>
2


In [20]:
import numpy as py
a=py.array([[[1,4,5,6,6],[2,12,3445,45,4],[3,45,78,9,3],[45,5,79,4,7],[56,2,3,5,7]]])
print(a)
print(a.ndim)

[[[   1    4    5    6    6]
  [   2   12 3445   45    4]
  [   3   45   78    9    3]
  [  45    5   79    4    7]
  [  56    2    3    5    7]]]
3
