In [ ]:
l=[1,2,3]
l2=[3,4,5]
c=[]
for i in range(len(l)):
   c=( l[i]+l2[i])
print(c)
    

In [3]:
import numpy as np
a=np.array([2,4,3,1,34])
b=np.array([3,67,4,56,3])
addition=a+b
print(addition)

[ 5 71  7 57 37]


In [6]:
import numpy as np
a=np.array([[23,45,68,89,24],[23,354,56,5,7]])
b=np.array([[23,344,566,78,2],[2,3,4,67,5]])
add=a+b
sub=a-b
mul=a*b
div=a/b
print(add)
print(sub)
print(mul)
print(div)

[[ 46 389 634 167  26]
 [ 25 357  60  72  12]]
[[   0 -299 -498   11   22]
 [  21  351   52  -62    2]]
[[  529 15480 38488  6942    48]
 [   46  1062   224   335    35]]
[[1.00000000e+00 1.30813953e-01 1.20141343e-01 1.14102564e+00
  1.20000000e+01]
 [1.15000000e+01 1.18000000e+02 1.40000000e+01 7.46268657e-02
  1.40000000e+00]]


In [8]:
import numpy as np
a=np.array([2,4,3,1,34])
b=np.array([3,67,4,56,3])
addition=a-b
print(addition)

[ -1 -63  -1 -55  31]
