In [1]:
import numpy as np
x=np.array([1,46,87,90,3,74,5,7,3,78])
n=x.reshape(2,5)
print(n)

[[ 1 46 87 90  3]
 [74  5  7  3 78]]


In [7]:
import numpy as np
n=np.array([234,45657,6989,3454,890,34546,567678,2])
s=n.reshape(4,2)
print(s)

[[   234  45657]
 [  6989   3454]
 [   890  34546]
 [567678      2]]


In [8]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
g=a.reshape(3,2,2)
print(g)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [10]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
g=a.reshape(6,1,2)
print(g)

[[[ 1  2]]

 [[ 3  4]]

 [[ 5  6]]

 [[ 7  8]]

 [[ 9 10]]

 [[11 12]]]


In [11]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
g=a.reshape(2,3,2)
print(g)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [12]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
g=a.reshape(1,3,4)
print(g)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
